### ISSUE TITLE
Was the autotile feature removed?

### ISSUE THREAD

**Issue by juacq97** [qewer33/Exquisite#15]
Hi! I remember a feature in old versions where you can click the background to automatically tile the windows, but now it was replaced by maximize when clicking the background. It was removed? I really liked that feature.

**Comment by qewer33** [comment]
You may be mistaking this project for another one, the background button was always maximize since release. But the autotiling feature is recently added and will become available in 0.4, you can look at the indev 0.4 changelog [here](https://github.com/qewer33/Exquisite/blob/main/CHANGELOG.md)

You can clone the repo and run `./install.sh` if you want to try it out before release, I haven't tested it properly yet so it'll be nice to see if works well from someone else's eyes
