### ISSUE TITLE
[Suggestion]Once a layout is defined, windows opened after that follow the order of the layout

### ISSUE THREAD

**Issue by Terkyz** [qewer33/Exquisite#7]
I don't know if it's possible with Kwin, but it seems to me that it could be useful to keep windows consistent when using Exquisite, which follows the pattern of opening as it used to or wherever

Thanks for doing this _Exquisite_ script!

**Comment by qewer33** [comment]
Do you mean you would select a layout and when you open new windows, the windows get tiled according to that layout?

**Comment by Terkyz** [comment]
Exactly!

**Comment by qewer33** [comment]
I feel like this as a feature would be over the main purpose of Exquisite (since Exquisite is meant as more of a manual tool rather than a window tiler) but I did ad an optional (enabled by default) "auto layout" feature with commit 6d2a0a3cc81737a87313c85cf6a756c030687f84 that can be used for a similar purpose. When you click the background button of a layout, it tiles the available non-minimized windows on the current desktop according to that layout. 
Currently needs a bit more testing but it will be available in the next release.
