### ISSUE TITLE
Allow gaps between windows

### ISSUE THREAD

**Issue by cazacugmihai** [qewer33/Exquisite#8]
![image](https://user-images.githubusercontent.com/89212/179358851-de48a58c-5f90-45e8-b9eb-848a7b34c083.png)

**Comment by qewer33** [comment]
Would be a really cool feature but frankly I have 0 clue on how to implement it, the placement math gets a bit tricky when gaps come into play. Having only a single gap value instead of top/bottom/left/right/between could make stuff simpler though.

@nclarius , would you mind helping here if you are free? Since you are also the creator of the Window Gaps script I'm guessing you know way more than I can try here :D

**Comment by nclarius** [comment]
I don't understand what the request is. I'm using both extensions, and gaps are applied just fine when tiling them with your script. cazacugmihai, what exactly is your issue?

**Comment by qewer33** [comment]
I think he meant adding gaps as a feature to Exquisite but I also tested using Window Gaps with it now and they seem to pair quite well. @cazacugmihai if it also works fine for you, you can close the issue

**Comment by cazacugmihai** [comment]
Yes, it works almost fine combining these two extensions (Windows Gaps still has this error: [Windows resize while moving them around](https://github.com/nclarius/tile-gaps/issues/15)). Thank you!
