### ISSUE TITLE
Buttons are not pixel-perfect

### ISSUE THREAD

**Issue by doncsugar** [qewer33/Exquisite#9]
The buttons shown are a little fuzzy. I haven't looked at the code, but I usually encounter this problem when I'm not rounding the sizes of elements.

You can see that the bottom button is blurry at the top and bottom:
![image](https://user-images.githubusercontent.com/46570709/179375275-405a6dbf-ff4c-4eb5-98e6-177409f77e24.png)
The theme in use is Desert-Plasma by l4k1.

**Comment by qewer33** [comment]
Not really that big of a problem imo since it's pretty unnoticeable but ig might annoy some people. Likely has something to do with the `SpanGridLayout` implementation I'm using. Tried rounding the size and placement of buttons but that causes alignment issues. Contributions are welcome if anyone wants to improve it.

**Comment by qewer33** [comment]
Closing this issue
